# Generated by Django 2.2.4 on 2020-08-11 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200807_2058'),
        ('pbltest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowcard',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Group'),
        ),
    ]
