# Generated by Django 2.2.4 on 2020-08-20 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200807_2058'),
        ('pbltest', '0003_testcard_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowcard',
            name='activate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.CreateActivate'),
        ),
    ]
