# Generated by Django 2.2.4 on 2020-08-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0004_rowcard_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcard',
            name='pdf',
        ),
    ]
