# Generated by Django 2.2.5 on 2020-06-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200623_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identify',
            field=models.CharField(choices=[('guest', '訪客'), ('teacher', '引導師')], default='guest', max_length=123),
        ),
    ]
