# Generated by Django 2.2.5 on 2020-07-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_createactivate_createclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createactivate',
            name='activate_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
