# Generated by Django 2.2.5 on 2020-07-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200714_1618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateClass',
            new_name='CreateClassName',
        ),
    ]
