# Generated by Django 2.2.5 on 2020-07-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200715_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='createclass',
            name='activate_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.CreateActivate'),
        ),
    ]
