# Generated by Django 2.2.5 on 2020-07-14 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_createclass_activate_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createclass',
            name='activate_class',
        ),
        migrations.AddField(
            model_name='createactivate',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.CreateClass'),
        ),
    ]
