# Generated by Django 2.2.5 on 2020-07-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20200715_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='createactivate',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='user_group', to='login.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identify',
            field=models.CharField(choices=[('guest', '學員'), ('teacher', '引導師')], default='guest', max_length=123),
        ),
    ]
