# Generated by Django 2.2.5 on 2020-07-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200721_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='user_id',
            field=models.ManyToManyField(blank=True, related_name='user_group', to='login.User'),
        ),
    ]
