# Generated by Django 2.2.5 on 2020-07-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_group_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user_id',
        ),
    ]
