# Generated by Django 2.2.5 on 2020-07-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_remove_group_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_user',
            field=models.ManyToManyField(blank=True, related_name='user_user', to='login.User'),
        ),
    ]
