# Generated by Django 2.2.5 on 2020-07-27 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_group_group_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
