# Generated by Django 2.2.5 on 2020-07-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_remove_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
