# Generated by Django 2.2.5 on 2020-07-28 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_remove_createactivate_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='activate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.CreateActivate'),
        ),
    ]
