# Generated by Django 2.2.5 on 2020-08-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='activate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='login.CreateActivate'),
        ),
    ]
