# Generated by Django 2.2.5 on 2020-08-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200806_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='activate',
            new_name='activate_id',
        ),
    ]
