# Generated by Django 2.2.4 on 2020-08-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200807_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='c_name',
            field=models.CharField(default='學生姓名', max_length=128),
        ),
    ]
