# Generated by Django 2.2.4 on 2020-09-01 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_c_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.CreateClass'),
        ),
    ]
