# Generated by Django 2.2.6 on 2020-05-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='請輸入標題', max_length=20)),
                ('cardauther', models.CharField(default='username', max_length=20)),
                ('context', models.TextField(default='請輸入卡片內容')),
                ('createcarddate', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
