# Generated by Django 2.2.5 on 2020-07-05 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200623_0924'),
        ('pbltest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCard',
            fields=[
                ('file_title', models.TextField()),
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UPCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='media/card/img/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='card/covers/')),
                ('class_material', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name_plural': 'Card'},
        ),
        migrations.RemoveField(
            model_name='card',
            name='cardauther',
        ),
        migrations.RemoveField(
            model_name='card',
            name='createcarddate',
        ),
        migrations.RemoveField(
            model_name='card',
            name='enabled',
        ),
        migrations.AddField(
            model_name='card',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
        migrations.AddField(
            model_name='card',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='card',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pbltest.UPCard'),
        ),
    ]
