# Generated by Django 2.2.6 on 2020-05-29 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('pbltest', '0002_auto_20200524_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMes',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.User')),
            ],
            bases=('login.user',),
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivateDetail',
        ),
        migrations.DeleteModel(
            name='CourseDetail',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
