# Generated by Django 2.2.6 on 2020-05-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0003_auto_20200529_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermes',
            name='activate_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
