# Generated by Django 2.2.5 on 2020-07-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0004_auto_20200706_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcard',
            name='base_img',
            field=models.CharField(max_length=65535),
        ),
    ]
