# Generated by Django 2.2.6 on 2020-06-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0004_usermes_activate_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMes',
        ),
    ]
