# Generated by Django 2.2.6 on 2020-06-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pbltest', '0005_delete_usermes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCard',
            fields=[
                ('file_title', models.TextField()),
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_address', models.CharField(max_length=100)),
            ],
        ),
    ]
