# Generated by Django 2.2.5 on 2020-07-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0005_auto_20200706_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcard',
            name='base_img',
            field=models.CharField(max_length=21845),
        ),
    ]
