# Generated by Django 2.2.6 on 2020-06-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0006_filecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='card/img/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='card/covers/')),
            ],
        ),
    ]
