# Generated by Django 2.2.6 on 2020-06-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0007_upcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcard',
            name='pdf',
            field=models.FileField(upload_to='media/card/img/'),
        ),
    ]
