# Generated by Django 2.2.5 on 2020-07-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0007_auto_20200706_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcard',
            name='base_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
