# Generated by Django 2.2.5 on 2020-07-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0008_auto_20200706_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcard',
            name='class_material',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
