# Generated by Django 2.2.5 on 2020-07-07 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0009_auto_20200707_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcard',
            name='base_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pbltest.Card'),
        ),
    ]
