# Generated by Django 2.2.6 on 2020-06-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0009_auto_20200609_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcard',
            name='pdf',
            field=models.FileField(upload_to='media/card/img/'),
        ),
    ]
