# Generated by Django 2.2.6 on 2020-06-11 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0011_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbltest.UPCard'),
        ),
    ]
