# Generated by Django 2.2.5 on 2020-07-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0011_row_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_date',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='published_date',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
