# Generated by Django 2.2.6 on 2020-06-16 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0011_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='context1',
        ),
        migrations.RemoveField(
            model_name='card',
            name='context2',
        ),
        migrations.RemoveField(
            model_name='card',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='group',
        ),
        migrations.RemoveField(
            model_name='card',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='card',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pbltest.UPCard'),
        ),
    ]
