# Generated by Django 2.2.6 on 2020-06-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0012_auto_20200617_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='context2',
            field=models.TextField(blank=True),
        ),
    ]
