# Generated by Django 2.2.6 on 2020-06-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0012_auto_20200617_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='context1',
            field=models.TextField(blank=True),
        ),
    ]
