# Generated by Django 2.2.6 on 2020-06-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0012_auto_20200612_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='group',
        ),
    ]
