# Generated by Django 2.2.5 on 2020-07-11 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0012_auto_20200711_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcard',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
