# Generated by Django 2.2.5 on 2020-07-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0013_auto_20200711_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcard',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/card/img/'),
        ),
    ]
