# Generated by Django 2.2.5 on 2020-07-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200623_0924'),
        ('pbltest', '0014_auto_20200711_1214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='row_Card',
            new_name='RowCard',
        ),
    ]
