# Generated by Django 2.2.5 on 2020-06-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0014_auto_20200617_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcard',
            name='class_material',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
