# Generated by Django 2.2.5 on 2020-07-14 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0015_auto_20200714_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcard',
            name='base_card1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pbltest.RowCard'),
        ),
    ]
