# Generated by Django 2.2.5 on 2020-07-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0016_testcard_base_card1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='published_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
