# Generated by Django 2.2.6 on 2020-06-16 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0016_auto_20200617_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='card',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
