# Generated by Django 2.2.5 on 2020-07-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0017_auto_20200715_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowcard',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rowcard',
            name='published_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
