# Generated by Django 2.2.5 on 2020-07-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0020_auto_20200721_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='context1',
            field=models.TextField(blank=True),
        ),
    ]
