# Generated by Django 2.2.6 on 2020-06-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0021_remove_card_context1'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='context1',
            field=models.TextField(blank=True),
        ),
    ]
