# Generated by Django 2.2.5 on 2020-07-28 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20200727_1128'),
        ('pbltest', '0022_rowcard_context2'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='activate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.CreateActivate'),
        ),
        migrations.AddField(
            model_name='card',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Group'),
        ),
    ]
