# Generated by Django 2.2.6 on 2020-06-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbltest', '0022_card_context1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='context1',
        ),
    ]
